/**
 * Games Registry for Expenses-Tracker Games Hub
 * Centralized list of casual and brain games available or upcoming in the app.
 */

export const GAMES_LIST = [
  {
    id: 'wrongway',
    title: 'Wrong Way',
    subtitle: "Don't be mad",
    description: 'Block paths with barricades, jump opponents, and sprint to the goal line!',
    icon: 'Swords',
    iconName: 'Swords',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    category: 'Strategy',
    badge: 'NEW 🔥',
    status: 'playable',
    route: 'WrongWayMenu',
  },
  {
    id: 'tictactoe',
    title: 'Tic Tac Toe',
    subtitle: 'Classic X & O',
    description: 'Play against smart AI or pass & play with a friend in local 2-player mode.',
    icon: 'X',
    iconName: 'Grid',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    category: 'Strategy',
    badge: 'Popular',
    status: 'ready', // ready to build/play
    route: 'TicTacToeGame',
  },
  {
    id: 'game2048',
    title: '2048',
    subtitle: 'Slide & Merge',
    description: 'Swipe tiles, combine matching numbers and race to reach the 2048 tile.',
    icon: 'Binary',
    iconName: 'LayoutGrid',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    category: 'Puzzle',
    badge: 'Brain',
    status: 'ready',
    route: 'Game2048',
  },
  {
    id: 'memory',
    title: 'Memory Match',
    subtitle: 'Card Flip Pair',
    description: 'Test and sharpen your visual memory by finding hidden matching pairs.',
    icon: 'Sparkles',
    iconName: 'Sparkles',
    color: '#10B981',
    bgColor: '#ECFDF5',
    category: 'Memory',
    badge: 'Relaxing',
    status: 'ready',
    route: 'MemoryMatchGame',
  },
  {
    id: 'snake',
    title: 'Retro Snake',
    subtitle: 'Arcade Classic',
    description: 'Guide your snake, munch apples to grow longer, and dodge the walls.',
    icon: 'Activity',
    iconName: 'Zap',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    category: 'Arcade',
    badge: 'Classic',
    status: 'ready',
    route: 'SnakeGame',
  },
  {
    id: 'wordguess',
    title: 'Word Guess',
    subtitle: '5-Letter Mystery',
    description: 'Guess the hidden 5-letter word in 6 attempts with color-coded hints.',
    icon: 'Type',
    iconName: 'Type',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    category: 'Word',
    badge: 'Daily',
    status: 'ready',
    route: 'WordGuessGame',
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    subtitle: 'Tactical Sweeper',
    description: 'Uncover clean squares using number clues while flagging the hidden mines.',
    icon: 'Flag',
    iconName: 'Flag',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    category: 'Logic',
    badge: 'Tactical',
    status: 'ready',
    route: 'MinesweeperGame',
  },
];
